- name: Install Dependencies from CPAN
  cpanm: name={{item}}
  with_items:
    - Bio::Perl
    - Bit::Vector
    - DBD::SQLite
    - DBI
    - Error
    - Error::Simple
    - File::NFSLock
    - File::Which
    - forks
    - forks::shared
    - Inline
    - Inline::C
    - IO::All
    - IO::Prompt
    - Perl::Unsafe::Signals
    - PerlIO::gzip
    - Proc::ProcessTable
    - Proc::Signal
    - threads
    - URI::Escape

- name: Install Dependencies from Apt
  apt: name={{item}}
  with_items:
    - ncbi-blast+
    - ncbi-blast+-legacy



#http://yandell.topaz.genetics.utah.edu/maker_downloads/8AB0/DB9A/F7F4/3DE5C1FC9204F76F8491CC138C45/maker-2.31.8.tgz
