- name: Download RMBlast
  shell: curl -O ftp://ftp.ncbi.nlm.nih.gov/blast/executables/rmblast/LATEST/ncbi-rmblastn-2.2.28-x64-linux.tar.gz"
  args:
    chdir="{{source_dir}}"

- name: Uncompress RMBlast
  unarchive:
    src="{{source_dir}}/ncbi-rmblastn-2.2.28-x64-linux.tar.gz"
    dest="{{software_dir}}"
    copy=no
    creates="{{software_dir}}/ncbi-rmblastn-2.2.28/LICENSE"

- name: Copy rmblastn to /usr/local/bin
  copy: src="{{software_dir}}/ncbi-rmblastn-2.2.28/bin/rmblastn" dest=/usr/local/bin/rmblastn


