- name: Downloading SNAP v{{version}}
  get_url: url="http://korflab.ucdavis.edu/Software/snap-2013-11-29.tar.gz" dest="{{source_dir}}/snap-2013-11-29.tar.gz"
  register: get_url_result
  until: "'OK' in get_url_result.msg or 'file already exists' in get_url_result.msg"
  retries: 5
  delay: 10

